# Generated by Django 3.2.7 on 2021-09-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='info',
            new_name='user_info',
        ),
    ]
