# Generated by Django 3.2.7 on 2021-09-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_rename_info_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='email',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='user_info',
            name='password',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
