# Generated by Django 3.2.7 on 2021-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='img/%y/<django.db.models.fields.CharField>'),
        ),
    ]
