# Generated by Django 3.2.7 on 2021-10-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_auto_20211001_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_name',
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='img/%y/<django.db.models.query_utils.DeferredAttribute object at 0x7f9789fe4c10>'),
        ),
    ]
