# Generated by Django 3.2.7 on 2021-10-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_auto_20211001_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='img/%y'),
        ),
    ]
