# Generated by Django 3.2.7 on 2021-10-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0011_alter_image_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='img/<django.db.models.query_utils.DeferredAttribute object at 0x7fcd1d869c10>'),
        ),
    ]
