# Generated by Django 3.2.7 on 2021-10-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0012_alter_image_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to='img/<django.db.models.fields.CharField>'),
        ),
    ]
