# Generated by Django 3.2.7 on 2021-10-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0014_auto_20211001_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
