# Generated by Django 3.2.7 on 2021-10-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0015_delete_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('email', models.CharField(default='', max_length=1000)),
                ('password', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
