# Generated by Django 3.2.7 on 2021-10-05 15:13

from django.db import migrations, models
import ocr.models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0016_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(upload_to=ocr.models.splitname),
        ),
    ]
